services:
  mirrorrelay:
    platform: linux/amd64
    build:
      context: .
      args:
        VERSION: ${MIRRORRELAY_VERSION:-0.0.16}
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    environment:
      MIRRORRELAY_ADMIN_HOST: ${MIRRORRELAY_ADMIN_HOST:-}
    volumes:
      - ./configs/config.docker.yaml:/etc/mirrorrelay/config.yaml:ro
      - /run/mirrorrelay:/run/mirrorrelay
      - mirrorrelay-data:/var/lib/mirrorrelay
      - mirrorrelay-cache:/var/cache/mirrorrelay
      - mirrorrelay-logs:/var/log/mirrorrelay

volumes:
  mirrorrelay-data:
  mirrorrelay-cache:
  mirrorrelay-logs:
